apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksdemo  # Name of the EKS Cluster
  region: ap-northeast-2
fargateProfiles:
  - name: fp-app3
    selectors:
      # All workloads in the "ns-app3" Kubernetes namespace will be
      # scheduled onto Fargate:      
      - namespace: ns-app3